scheme: Gemini
darkmode: true

google_analytics:
  tracking_id: G-R9EX3586LZ
  only_pageview: false

github_banner:
  enable: true
  permalink: https://github.com/crutcher

menu:
    home: / || fa fa-home
    archives: /archives/ || fa fa-archive
    tags: /tags/ || fa fa-tags

favicon:
  small: /images/amp16.png
  medium: /images/amp32.png
  apple_touch_icon: /images/amp32.png
  safari_pinned_tab: /images/amp32.png

codeblock:
  theme:
    light: default
    dark: stackoverflow-dark

  prism:
    light: prism
    dark: prism-dark
