scheme: Gemini
darkmode: true

back2top:
  enable: true

post_navigation: true

google_analytics:
  tracking_id: G-R9EX3586LZ
  only_pageview: false

github_banner:
  enable: false
  permalink: https://github.com/crutcher

# Icons from: https://fontawesome.com/
# <url> || fa fa-<id>
menu:
  Home: / || fa fa-home
  Atom: /atom.xml || fab fa-atom
  Archives: /archives/ || fa fa-archive
  Tags: /tags/ || fa fa-tags
  Tapestry: /Tapestry/ || fa fa-diagram-project
  Resume: /Resume/ || fa fa-solid fa-file

font:
  enable: true

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: PT Sans
    size: 1.125

  # Font settings for site title (.site-title).
  title:
    external: true
    family: Fira Sans
    size:

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: true
    family: Roboto Slab
    size:

  # Font settings for posts (.post-body).
  posts:
    external: true
    family: PT Sans

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: Fira Code


social:
  GitHub: https://github.com/crutcher || fab fa-github
  Mastodon: https://sigmoid.social/@crutcher || fab fa-mastodon
  Discord: https://discordapp.com/users/361021789268344842 || fab fa-discord
  LinkedIn: https://www.linkedin.com/in/crutcher-dunnavant-4841ba9/ || fab fa-linkedin

favicon:
  small: /images/amp16.png
  medium: /images/amp32.png
  apple_touch_icon: /images/amp32.png
  safari_pinned_tab: /images/amp32.png

codeblock:
  theme:
    light: default
    dark: stackoverflow-dark

  prism:
    light: prism
    dark: prism-dark

disqus:
  enable: true
  shortname: crutcher-github-io
  count: true

comments:
  style: buttons
  active: disqus
  storage: true
  layzload: false
  nav:
    disqus:
      text: Load Disqus
      order: -1
